[env]
WINIT_UNIX_BACKEND = "wayland"

[window]
decorations = "none"
opacity = 0.67
startup_mode = "Windowed"
dynamic_padding = false
title = "Alacritty"
class = { instance = "Alacritty", general = "Alacritty" }

[window.padding]
x = 4
y = 4

[window.dimensions]
columns = 132
lines = 34

[font]
size = 15.5
builtin_box_drawing = true

[font.normal]
family = "Fira Code"
style = "Medium"

[font.bold]
family = "Fira Code"
style = "Semibold"  

[font.italic]
family = "Fira Code"
style = "Regular"

[font.bold_italic]
family = "Fira Code"
style = "Bold Italic"  

[font.offset]
y = 6 

[font.glyph_offset]
y = 2

[scrolling]
history = 10000
multiplier = 3

[cursor]
style = { shape = "Block", blinking = "Never" }
unfocused_hollow = true
thickness = 0.15

[colors.primary]
foreground = "#d9e0ee"
background = "#000000"  

[colors.cursor]
text = "#000000"
cursor = "#ffffff"

[colors.selection]
text = "#e0def4"
background = "#3e4e80"

[colors.normal]
black   = "#161320"
red     = "#f28fad"
green   = "#abe9b3"
yellow  = "#f6c177"
blue    = "#96cdfb"
magenta = "#d4a5fd"
cyan    = "#b5e8e0"
white   = "#d9e0ee"

[colors.bright]
black   = "#6e6a86"
red     = "#f28fad"
green   = "#abe9b3"
yellow  = "#f6c177"
blue    = "#96cdfb"
magenta = "#d4a5fd"
cyan    = "#b5e8e0"
white   = "#ffffff"

[mouse]
hide_when_typing = true

[bell]
animation = "EaseOut"
duration = 0
color = "0x000000"
command = "None"

[debug]
render_timer = false
log_level = "Warn"

# Scroll shortcuts (Kitty-inspired)
[[keyboard.bindings]]
key = "PageUp"
action = "ScrollPageUp"

[[keyboard.bindings]]
key = "PageDown"
action = "ScrollPageDown"

[[keyboard.bindings]]
key = "K"
mods = "Control|Shift"
action = "ScrollLineUp"

[[keyboard.bindings]]
key = "J"
mods = "Control|Shift"
action = "ScrollLineDown"

[[keyboard.bindings]]
key = "Home"
mods = "Control|Shift"
action = "ScrollToTop"

[[keyboard.bindings]]
key = "End"
mods = "Control|Shift"
action = "ScrollToBottom"

